
## 研究テーマの選び方

プレゼミの達成目標は、経営事象に関する問題を発見し、その問題がなぜ生じているのか、どうすれば解決できるのかを考えることができるようになることです。
そこで、まずは研究課題の種類について学びます。
問いの立て方には大きく分けて3つのタイプがあります。

1. 実証的問題
2. 規範的問題
3. 分析的問題

この3種類の問題について説明します。

- 「よい研究テーマ」の選び方を理解すること

「よい研究テーマ」の探し方を理解したらよい研究テーマが見付かるわけではないで、自分が面白い！と思えるような、興味引かれるテーマを見つけることが重要です。


## リサーチ・クエスチョンの種類

**リサーチ・クエスチョン**(research question)とは、研究対象となる会計に関する、抽象度の高い問いのことです。
リサーチ・クエスチョンが決まれば、その問いに答えるために、何をするべきなのかが決まるため、非常に重要な要素となります。
たとえば、

- 会計情報の質が高いと、投資家の意思決定がよりよいものになるのか？
- 大きな監査法人は、財務報告の質を高めているのか？
- CSR活動に積極的な会社は、納税も積極的か？
- のれんは償却するべきか？
- IFRS採用企業と非採用企業の違いはあるのか？
- コロナ禍における利益圧縮活動は行われたのか？

これらのリサーチ・クエスチョンを3つに分類してみましょう。


### 実証的問題

実証的問題では、**事実**を調べることが目的となります。
たとえば、「のれんの非償却はM&Aを促進させるのか」という問いに対しては、のれんの非償却を行っている企業と、行っていない企業のM&Aの実施率を比較することで、その問いに答えることができます。

実証的問題を扱う会計研究でも、定量的な研究だけでなく、インタビューによる定性的な研究もあります。参与観察研究はあまり見ません。
**事実**に注目する研究となるため、主観的な要素はできるだけ排して、観察されたデータや発言といった**客観的なデータ**を用いることが多いです。
このプレゼミでは、主として経営学分野における実証的問題を扱います。


### 規範的問題

いわゆる「べき論」を扱う問題で、日本の会計研究では今でも盛んに行われている研究です。
たとえば、「のれんは償却すべきか」という問いに対しては、のれんの償却を行うことで、どのようなメリットがあるのか、どのようなデメリットがあるのかを考え、そのメリットとデメリットを比較することで、その問いに答えることができます。
ただ、この場合でも、「誰にとっての」メリットを重視するべきなのか、という問題がでますが、そこは研究者の価値判断によって決まることになり、研究者の主観が大きく反映されることになります。

したがって教科書でも、規範的問題を実証的問題に変換する方法を考え、規範的問題を直接あつかう研究課題は取りあげません。

### 分析的問題

分析的問題は、まだ起こっていない、観察されていない現象を扱います。
そもそも起こっていない現象なのでデータも取りようがありません。
そこで、分析的問題では、**モデル**(model)を用いて、現象の起こりうるメカニズムを考えます。

基本的には、関心のある問題を抽象化して数式で表現し、前提条件と仮定を設定し、その問題を解くことで得られた結果を解釈することで、その問いに答えることができます。
たとえば、税務会計や監査といった情報が入手困難な領域において、ゲーム理論や契約理論、最適化理論を用いた分析が行われることが多いような気がしますが、そこまで詳しくないでし、難しいので、ここでは扱いません。

したがって、このプレゼミでは、各自がたてた実証的問題について考えていきます。

## 「よい研究テーマ」の見つけ方

政治学のMonroe (2000, pp.8--10)によると、

1. 明快さ
2. 検証可能性
3. 理論的重要性
4. 実用性
5. 独創性

がよい研究テーマに必要な要素らしいです。

詳しくは教科書を読むとして、会計学や経営学でもほぼ同じですが、卒業論文においては、**理論的重要性**と**独創性**はあればよいですが、必ずしも必要ではありません。
なぜなら、**理論的重要性**を理解し、論文で示すことは、研究で用いる推論の背後にある理論や仕組みを完全に理解する必要がありますし、**独創性**を主張するためには、膨大な先行研究を読み、自分の主張が他の人とどう違うのか、どの点が新しいのかを明らかにする必要があり、とても時間がかかるからです。

したがって、明快な推論で導き出された仮説を、客観的なデータを用いて、適切な手法で分析し、その結果を解釈し、経営実務にどういう影響があるのか、を主張できれば、卒業論文としては申し分ないレベルです。

とりわけ、このプレゼミでは、**検証可能性**を重視します。
そのレポート・論文を読めば、他の人でも同じ分析を行うことが可能であり、誰でも追試が行えることが重要です。
データの集め方や変数の作り方、データ分析のプロセスが明確にしめされており、それを自分でもすぐに再現することが重要です。そのために`R`は非常に有効なツールとなります。

### 規範的問題から実証的問題への変換

「べき論」は研究者の価値判断が大きく反映され、その研究者が主張する価値は主観的なものになるため検証ができません。
そこで規範的問題を実証的問題になるように問い方を変える方法を考えます。

<!-- #### 参照枠組みを変える -->
1つめの方法は、参照枠組みを変える方法です。
「会計は投資意思決定に役立つべきである」という問いは規範的問題で、それは「会計は株主のためのものである」という価値判断が含まれています。このままでは検証できないので、「会計は投資意思決定に役に立っているのか？」に変えることで、検証可能な問いになります。

<!-- #### 規範的問題の背後にある前提条件に注目する -->

2つめの方法は、規範的問題の前提条件に注目する方法です。
「会計は投資意思決定の役立つべきである」という規範的記述の背後には、

1. 会計は投資家のためのものである
2. 投資家が会計(情報)を使えば儲かる。
3. 投資家の投資が活発になれば、経済は活性化する。

という前提条件があると考えられます。
これを実証的な問題にするには、

1. 会計(情報)の主な利用者は投資家なのか？
2. 会計情報を使えば儲かるのか？
3. 投資の役に立つ会計情報を提供することで、経済は活性化するのか？

のように、規範的問題の背後にある前提条件を検証可能な問いに変えることで、実証的な問題になります。

### パズルを探す

パズル(puzzle)とは、ある現象を説明するために、既存の理論では説明できない現象のことです。
たとえば、配当パズル(dividend puzzle)とは、配当がなぜ存在するのか、という問題です。
配当は、株主に対する利益配分の一つであり、株主にとっては配当が高いほうがよいはずです。しかし、実際には、配当が高いほど株価が低くなるという現象が観察されます。
このような現象を説明するために、既存の理論では説明できないので、パズルと呼ばれ、研究題材としては非常に魅力的です。

### 研究論文の構成

実証研究の論文構成は、ほぼ以下のような構成となっています。

1. イントロダクション
2. 先行研究
3. 理論
4. 仮説
5. 対抗仮説
6. 作業化
7. 証拠
8. 結論

このうち、1-4は、研究の背景を説明する部分であり、5-7は、研究の主要な部分であり、8は、研究のまとめです。