# 計量会計学？

第1回講義の到達目標は、

1. 実証研究とはどんなものかを理解し、他人に説明できる。
2. 実証研究で扱える研究課題を理解し、研究課題を適切に設定できる。
3. 良い研究課題が持つべき特性を理解し、その特徴を備えた研究課題を設定できる。

第1回講義の到達度検証のための課題は、以下の通りです。

1. 定量データを用いて行う実証研究の利点と欠点を説明する。
2. 自分が興味をもてそうな研究課題を設定する。
3. 上で立てた研究課題がよい研究課題かどうかを5つの観点から検討し、評価する。

## 会計を計量する？

ここでは、教科書「Rによる計量政治学」の内容を「会計学」に置き換えて考えてみます。
「計量会計学」という言葉は一般的ではなく、会計学の世界では「**実証的会計研究**」とか「**実証会計学**」いう言葉が使われています。

社会科学において、社会で生じる様々な現象（たとえば、経営現象や会計実務）を、数値化して分析することを**計量化**(quantification)と呼びます。
計量化されたデータを用いて、社会現象を説明しようとするアプローチを**計量分析**(quantitative analysis)と呼びます。
計量分析の手法は、統計学や計量経済学などの数理的な手法を用いて、社会現象を説明しようとするものです。

**会計**とは経営活動から生み出される価値の変化を貨幣的に計測・記録し、その情報を整理し、集約することで、最終成果物として報告書(たとえば貸借対照表など)を作成し、それを利害関係者に報告することで、投資意思決定に役立つ情報を提供したり、利害関係者間の利害調整を行うことを目的とした一連のプロセスを意味します。
つまり会計そのものが、経営現象を計量化することを目的としているため、その最終成果物である財務諸表は、経営現象を計量化したデータの集合体と言えます。
この会計という経営実務を研究対象とした学問を**会計学**(accounting)といいます。
経営現象を研究対象とする経営学研究のうち、会計という経営実務に焦点を当てた会計研究を、計量分析の手法を用いて行うことを**実証会計学**(empirical accounting)と呼びます。

とりわけ会計学の中でも、公表された会計情報といった計量化されたデータを用いた研究を(狭義の)**実証的会計研究**(archival based empirical accounting research)とか、単に**実証会計**といいます[^1] 。


[^1]:  ちなみに(広義の)事実解明的な会計研究(positive accounting research)とは、会計実務を説明し予想するための理論の構築を目指す学問を指す会計研究を意味します。いまのところは、特に覚える必要はないです。

    他にも、事実解明的な会計研究として、数理モデルを用いた分析的会計研究(analytical accounting research)、実験経済を用いた実験会計研究(experimental accounting research)、行動科学の理論を用いた会計研究(behavioral accounting research)があります。

    その他にも、簿記を研究対象とした簿記論、会計計算の仕組みを研究する計算構造研究、会計の歴史を研究する会計史など様々な研究分野があります。

国際的に評価の高い会計学の学術誌である、*The Accounting Review*(TAR)、*Journal of Accounting and Economics*(JAE)、*Journal of Accounting Research*(JAR)、*Review of Accounting Studies*(RAST)、*Contemporary Accounting Research*(CAR)の五大誌に掲載されている論文の大部分が、会計情報を用いた計量分析となっています。
ただこの5誌はすべて北米の研究機関や大学が発行している雑誌ですので、実証、実験、分析的な会計研究がメインストリームの扱いとなりますが、ヨーロッパでは、
*Accounting, Organisation snd Society*(AOS)、*European Accounting Research*(EAR)、*British Accounting Research*(BAR)、*Critical Accounting Research*(CAR)といった、定性的研究も重要視し、経済学ではなく社会学をベースとした研究が主流？となっている雑誌もあります。しかし松浦は社会学について語れる知識がないので、やはり沈黙します。


## 分析的会計研究と実証的会計研究

会計研究の世界では、1960年頃までは規範的研究(normative research)という「〇〇するべき」という主張をする研究が主流でした。たとえば企業が保有する株式を時価評価すべきかとか、ある特徴をもつリース資産を購入したものとして扱うべきか、といったものです。

しかし、1968年にJournal of Accounting Researchに掲載された*Ball and Brown (1968) An Empirical Evaluation of Accounting Income Numbers*を皮切りに、実際に会計情報は投資家の役に立っているのかをデータを使って確かめる、という、いわゆる実証研究が行われるようになり、今日まで会計研究の主要分野となっています。

実証的会計研究を行うために必要な知識・技術として、

- 会計基準・会計理論
- ミクロ経済学（ゲーム理論、契約理論、情報の経済学）
- 計量経済学
- ファイナンス理論（コーポレート・ファイナンス）
- プログラミング

が挙げられます。

同じ事実解明型研究の中でも、証拠では無く論理による主張を目指す分析的会計研究で必要な知識・技術として、

- 会計基準・会計理論
- ミクロ経済学（ゲーム理論、契約理論、情報の経済学）
- 最適化理論
- 差分方程式

が挙げられます。
そもそも分析的会計研究は、会計現象を抽象化し、数学でその現象を表現するモデルを作り、そのモデルを解くことで得られる均衡解を比較静学することで様々なインプリケーションを得るため、実際に発生していない問題も研究することできる利点があります。
その反面、要求されるモデルを作るセンスや、解けるモデルを構築するための数学レベルも高く、また研究に要する時間も長いため、実証的会計研究に比べて論文が少ないです。
しかし、理論と実証は研究の両輪をなすものであり、どちらも重要であることに違いはないので、完全に理解することはできなくても、目を通す努力は必要でしょう。

ただやはり難しい数式が出てくる会計研究は松浦には完全に理解することはできないので、ここでは実証的会計研究について考えていきます。ヴィトゲンシュタインの言葉を借りれば、語り得ないものは語らないということで、分析的会計研究は沈黙するべきです。

## 研究テーマの選び方

プレゼミの達成目標は、経営事象に関する問題を発見し、その問題がなぜ生じているのか、どうすれば解決できるのかを考えることができるようになることです。
そこで、まずは研究課題の種類について学びます。
問いの立て方には大きく分けて3つのタイプがあります。

1. 実証的問題
2. 規範的問題
3. 分析的問題

この3種類の問題について説明します。

- 「よい研究テーマ」の選び方を理解すること

「よい研究テーマ」の探し方を理解したらよい研究テーマが見付かるわけではないで、自分が面白い！と思えるような、興味引かれるテーマを見つけることが重要です。


## リサーチ・クエスチョンの種類

**リサーチ・クエスチョン**(research question)とは、研究対象となる会計に関する、抽象度の高い問いのことです。
リサーチ・クエスチョンが決まれば、その問いに答えるために、何をするべきなのかが決まるため、非常に重要な要素となります。
たとえば、

- 会計情報の質が高いと、投資家の意思決定がよりよいものになるのか？
- 大きな監査法人は、財務報告の質を高めているのか？
- CSR活動に積極的な会社は、納税も積極的か？
- のれんは償却するべきか？
- IFRS採用企業と非採用企業の違いはあるのか？
- コロナ禍における利益圧縮活動は行われたのか？

これらのリサーチ・クエスチョンを3つに分類してみましょう。


### 実証的問題

実証的問題では、**事実**を調べることが目的となります。
たとえば、「のれんの非償却はM&Aを促進させるのか」という問いに対しては、のれんの非償却を行っている企業と、行っていない企業のM&Aの実施率を比較することで、その問いに答えることができます。

実証的問題を扱う会計研究でも、定量的な研究だけでなく、インタビューによる定性的な研究もあります。参与観察研究はあまり見ません。
**事実**に注目する研究となるため、主観的な要素はできるだけ排して、観察されたデータや発言といった**客観的なデータ**を用いることが多いです。
このプレゼミでは、主として経営学分野における実証的問題を扱います。


### 規範的問題

いわゆる「べき論」を扱う問題で、日本の会計研究では今でも盛んに行われている研究です。
たとえば、「のれんは償却すべきか」という問いに対しては、のれんの償却を行うことで、どのようなメリットがあるのか、どのようなデメリットがあるのかを考え、そのメリットとデメリットを比較することで、その問いに答えることができます。
ただ、この場合でも、「誰にとっての」メリットを重視するべきなのか、という問題がでますが、そこは研究者の価値判断によって決まることになり、研究者の主観が大きく反映されることになります。

したがって教科書でも、規範的問題を実証的問題に変換する方法を考え、規範的問題を直接あつかう研究課題は取りあげません。

### 分析的問題

分析的問題は、まだ起こっていない、観察されていない現象を扱います。
そもそも起こっていない現象なのでデータも取りようがありません。
そこで、分析的問題では、**モデル**(model)を用いて、現象の起こりうるメカニズムを考えます。

基本的には、関心のある問題を抽象化して数式で表現し、前提条件と仮定を設定し、その問題を解くことで得られた結果を解釈することで、その問いに答えることができます。
たとえば、税務会計や監査といった情報が入手困難な領域において、ゲーム理論や契約理論、最適化理論を用いた分析が行われることが多いような気がしますが、そこまで詳しくないでし、難しいので、ここでは扱いません。

したがって、このプレゼミでは、各自がたてた実証的問題について考えていきます。

## 「よい研究テーマ」の見つけ方

政治学のMonroe (2000, pp.8--10)によると、

1. 明快さ
2. 検証可能性
3. 理論的重要性
4. 実用性
5. 独創性

がよい研究テーマに必要な要素らしいです。

詳しくは教科書を読むとして、会計学や経営学でもほぼ同じですが、卒業論文においては、**理論的重要性**と**独創性**はあればよいですが、必ずしも必要ではありません。
なぜなら、**理論的重要性**を理解し、論文で示すことは、研究で用いる推論の背後にある理論や仕組みを完全に理解する必要がありますし、**独創性**を主張するためには、膨大な先行研究を読み、自分の主張が他の人とどう違うのか、どの点が新しいのかを明らかにする必要があり、とても時間がかかるからです。

したがって、明快な推論で導き出された仮説を、客観的なデータを用いて、適切な手法で分析し、その結果を解釈し、経営実務にどういう影響があるのか、を主張できれば、卒業論文としては申し分ないレベルです。

とりわけ、このプレゼミでは、**検証可能性**を重視します。
そのレポート・論文を読めば、他の人でも同じ分析を行うことが可能であり、誰でも追試が行えることが重要です。
データの集め方や変数の作り方、データ分析のプロセスが明確にしめされており、それを自分でもすぐに再現することが重要です。そのために`R`は非常に有効なツールとなります。

### 規範的問題から実証的問題への変換

「べき論」は研究者の価値判断が大きく反映され、その研究者が主張する価値は主観的なものになるため検証ができません。
そこで規範的問題を実証的問題になるように問い方を変える方法を考えます。

<!-- #### 参照枠組みを変える -->
1つめの方法は、参照枠組みを変える方法です。
「会計は投資意思決定に役立つべきである」という問いは規範的問題で、それは「会計は株主のためのものである」という価値判断が含まれています。このままでは検証できないので、「会計は投資意思決定に役に立っているのか？」に変えることで、検証可能な問いになります。

<!-- #### 規範的問題の背後にある前提条件に注目する -->

2つめの方法は、規範的問題の前提条件に注目する方法です。
「会計は投資意思決定の役立つべきである」という規範的記述の背後には、

1. 会計は投資家のためのものである
2. 投資家が会計(情報)を使えば儲かる。
3. 投資家の投資が活発になれば、経済は活性化する。

という前提条件があると考えられます。
これを実証的な問題にするには、

1. 会計(情報)の主な利用者は投資家なのか？
2. 会計情報を使えば儲かるのか？
3. 投資の役に立つ会計情報を提供することで、経済は活性化するのか？

のように、規範的問題の背後にある前提条件を検証可能な問いに変えることで、実証的な問題になります。

### パズルを探す

パズル(puzzle)とは、ある現象を説明するために、既存の理論では説明できない現象のことです。
たとえば、配当パズル(dividend puzzle)とは、配当がなぜ存在するのか、という問題です。
配当は、株主に対する利益配分の一つであり、株主にとっては配当が高いほうがよいはずです。しかし、実際には、配当が高いほど株価が低くなるという現象が観察されます。
このような現象を説明するために、既存の理論では説明できないので、パズルと呼ばれ、研究題材としては非常に魅力的です。


### 研究論文の構成

論文の構成

1. イントロダクション
2. 先行研究
3. 理論
4. 仮説
5. 対抗仮説
6. 作業化
7. 証拠
8. 結論

