# はじめに {.unnumbered}

この本は、プレゼミのメインテキストである浅野・矢内 (2020)「**Rによる計量政治学**」の学習用ノートです。
あと、サブテキストであるウィラワン・勝又 (2023)「**Rによるマーケティング・データ分析**」の一部の内容も含まれています。
基本的に松浦が自分の勉強用に作成したノートのため、誤りや不備が含まれている可能性が高いです。
また、このノートは、浅野・矢内 (2020)やウィラワン・勝又 (2023)の内容を網羅しているわけではないので、このノートを使う場合は教科書を手元において、学習することをおすすめします。

なぜ会計学を専門とする松浦のプレゼミで、メインの教科書が「Rによる計量政治学」なのかというと、このテキストが社会科学の一分野である政治学という経営学部生にとっても関連のある興味深い題材を用いて、計量経済学の基礎から応用までをRで実装するための知識を習得できるものだからです。

とりわけ第1部の第2章「研究テーマの選び方」と第3章「理論と仮説」は、卒業論文を書く際にも非常に重要となる内容ですので、全経営学部生によんでもらいたい内容です。
第4章「Rの使い方」と第5章「Rによるデータ操作」は、本書の学習に必要な必要最小限の内容ですので、他の教科書やウェブサイトを参考にして、より詳細な内容を学習したほうが良いですが、この内容を理解し、使えるようになれば、MS Excelを使わずにRだけで分析できるようになるでしょう。

第6章から第15章までが、統計学から計量経済学の内容となります。
おおよそ、代表的な統計量の計算や、グラフを使ったデータの理解、標本(sample)を用いた母集団(population)の推定や仮説検定、複数の統計量の関係性の理解、因果関係を分析する手法の1つである回帰分析の基礎と応用、2値選択の問題を推定するためのロジスティック関数の使い方などを学習します。

ここまでの内容の学習にプレゼミ15回のうちおおよそ11回を使います。
12回〜15回の4回は多変量解析手法として因子分析やクラスター分析、機械学習を用いた判別モデルとして決定木分析を学習します。
2年生終了時点で、ここまでの内容を修得していれば、卒業論文の分析に必要な知識はほぼ習得できていると考えて良いでしょう。あとは関心のある研究テーマを選ぶために、面白そうな専門演習(ゼミ)に入って、Rと統計学・計量経済学を使った実証研究を楽しんでくれれば、プレゼミの目標が達成されます。


プレゼミのスケジュールはおおよそ以下の通りです。

- 第1回 実証会計学とは
- 第2回 研究テーマの選び方・理論と仮説
- 第3回 理論と仮説
- 第4回 Rの使い方とRによるデータ操作
- 第5回 記述統計とデータの可視化・視覚化
- 第6回 統計的推定と統計的仮説検定
- 第7回 変数間の関連性
- 第8回 回帰分析の基礎と統計的推定
- 第9回 回帰分析の応用
- 第10回 交差項の使い方
- 第11回 ロジスティック関数
- 第12回 質問紙の作成と測定尺度
- 第13回 因子分析
- 第14回 クラスター分析
- 第15回 決定木 (時間があれば)

## 補足 {.unnumbered}

本ノートは、Posit社(以前はRstudio社)が開発した**Quarto**というソフトウェアを使って作成されています。Quartoとは、`RMarkdown`の記法で書かれたテキストファイルを、`knitr`というソフトウェアを介して、HTMLやPDF、MS Word、EPUBなどのファイルを作成するためのソフトウェアです。

最大の特徴は、MS ExcelとMS Wordのようにデータを分析する場所と文章を書く場所が別々ではなく、一つの画面の中でデータ分析とレポート・論文執筆を同時に行える、というものです。

また、`R`だけでなく、`Python`や`Julia`といった他のプログラミング言語も文章内に埋め込むことができるため、データ分析と文章執筆を統合させる環境として非常に優れています。
プレゼミでも、`Quarto`を使って最終レポートの作成を行う予定です。
`Quarto`は今も開発が進んでいる新しいレポート作成ソフトウェアなので、情報が少ないことが難点ですが、[公式サイト](https://quarto.org/)と[私たちのR](https://www.jaysong.net/RBook/)を見れば大抵のことは分かります。